spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/book?serverTimezone=UTC
    username: root
    password: 123456
  thymeleaf:
    encoding: UTF-8
    cache: false
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/META-NF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/


mybatis-plus:
  type-aliases-package: com.cssl.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: FULL
    use-generated-keys: true
    lazy-loading-enabled: true
  global-config:
    db-config:
      id-type: auto
server:
  port: 8081
