server:
  port: 7003


mybatis:
  type-aliases-package: com.cssl.pojo
  configuration:
    use-generated-keys: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  application:
    name: order-provider
  cloud:
    nacos:
      discovery:
        server-addr:  127.0.0.1:8848

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book?serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    #password: 123456
    database: 0
    timeout: 10s
    jedis:
      pool:
        max-idle: 50          # 最大空闲连接数
        min-idle: 10          # 最小空闲连接数
        max-wait:  -1s        # 等待可用连接的最大时间，负数为不限制
        max-active: -1        # 最大活跃连接数，负数为不限制

  jms:
    pub-sub-domain: false        # 配置消息的类型，如果是true则表示为topic消息否则是queue，默认false
  activemq:
    user: system                # 连接用户名
    password: manager            # 连接密码
    broker-url: tcp://localhost:61616   # 消息组件的连接主机信息
    pool.enabled: false        # 默认false,true要引入依赖activemq-pool
    in-memory: true            # 是否是内存模式，默认为true
    packages:
      trust-all: true            #序列化所有

#http://127.0.0.1:8881/actuator/nacos-discovery
management:
  endpoints:
    web:
      exposure:
        include: "*"
